<?php

/**
 * @file
 * Install hooks for commerce_installments.
 */

/**
 * Implements hook_field_schema().
 *
 * Defines the database schema of the field, using the format used by the
 * Schema API.
 *
 * @see http://drupal.org/node/146939
 * @see schemaapi
 * @see hook_field_schema()
 * @ingroup field_example
 */

function commerce_installments_field_schema($field) {
  if ($field['type'] == 'commerce_installments_payment') {
    return array(
      'columns' => array (
        'due_date' => array (
          'description' => 'The Unix timestamp of the payment due date.',
          'type' => 'int',
          'not null' => TRUE,
          'default' => 0,
        ),
        'amount' => array (
          'description' => 'The amount due for this payment.',
          'type' => 'int',
          'not null' => TRUE,
          'default' => 0,
        ),
      ),
    );
  }
}
